site_name: IBM Cloud Satellite Tutorials
nav:
  - Home: 'index.md'
  - Deploy Satellite: 'Satellite/satellite.md'
  - CP4D on Satellite: 'CP4D/satellite-cp4d.md'
  - Expose an Application with a Load Balancer: 'LB/satellite-lb.md'
  - Create VPC Infrastructure for Satellite: 'VPC/vpc.md'
  - Connect a private location with VPN: 'VPN/vpn.md'

theme:
  name: material
  palette:
    - scheme: default
      primary: blue